### ISSUE TITLE
Table is not coming across to Obsidian

### ISSUE THREAD

**Issue by SynapticDreams** [jgchristopher/obsidian-clipper#21]
Tried this multiple times, but the table will not output to Obsidian with or without additional text selected. Even a portion of the table (excluding headings etc) will not work either.

Eg. Site tested [here](https://trickmenot.ai/best-a-i-copywriting-and-seo-tools-for-every-level-and-every-budget/)

Latest versions as of 1st of April 2023 for Advanced Tables, Obisidian Clipper and Obsidian. Also using new bookmarklet.

**Comment by jgchristopher** [comment]
Can you share the browser you are using. I was able to successfully select several tables on this website and have them added to Obsidian properly.

**Comment by SynapticDreams** [comment]
Browser was Chrome 111

**Comment by jgchristopher** [comment]
I will get my Windows machine back in working order and test things out.

**Comment by jgchristopher** [comment]
Thanks for posting. Tested on Windows yesterday and see that things are pretty broken. I have a pretty good idea why. I should be able to get a fix out in a few days.

**Comment by jgchristopher** [comment]
I have some good news and some bad (neutral) news.  

The good news is that I have code in test that should fix most of the problems you encountered in Chrome on Windows. I plan to get this finished up and deployed in the next couple of days. 

The bad news is that I can't completely fix some of the issues you see in Chrome on Windows because Chrome-based browsers on Windows limit how long a URL can be (roughly 2000 characters), and this plugin sends the highlighted data as part of the URL. I verified that Firefox on Windows doesn't have this issue.

**Comment by SynapticDreams** [comment]
I will give Firefox a try then too :)

Thanks heaos for looking into this one :)

**Comment by jgchristopher** [comment]
Should be fixed in 0.0.7 #24
