### ISSUE TITLE
Clipped entry template field clears out when changing tabs in settings

### ISSUE THREAD

**Issue by benvenker** [jgchristopher/obsidian-clipper#39]
Whenever I fill in the template file location and navigate to a different settings tab, the input field clears.

This is presumably a problem for correctly configuring the chromium extension, since the input clears as soon as I click on the browser tab.

![CleanShot 2023-07-19 at 09 57 27](https://github.com/jgchristopher/obsidian-clipper/assets/4605817/9e753127-a31a-42e2-a180-d00db4abdcb0)

**Comment by jgchristopher** [comment]
This is odd. I notice a couple of things, which just highlight that I need to get an updated video/docs for the plugin. 

1. In the Daily Note Header, just enter `Links` instead of `# Links`
2. The template entry field should autocomplete and it uses the template you select to set the value. So just enter `Utility` and it should show options. The `./` doesn't work

**Comment by benvenker** [comment]
That worked! Sorry for the trouble, I must've been doing exactly the wrong things repeatedly to have not ever gotten these right 🙃
